variable "sg_Frontend1" {} 
variable "Frontend_port_1" {}
variable "Frontend_port_2" {}
variable "Frontend2" {}
variable "sg_Frontend2" {} 
variable "sg_Frontend1_ingress_port_1" {}
variable "sg_Frontend2_ingress_port_2" {}
variable "sg_Frontend1_ingress_port_1" {}
variable "sg_Frontend2_ingress_port_2" {}
variable "security_group_name" {} 