variable "Backend1_name" {}
variable "Backend2_name" {}
variable "Frontend2_name" {}
variable "Frontend1_name" {}
variable "ingress_port_1" {}
variable "ingress_port_2" {}
variable "sg_name" {}
variable "my-machines-lb" {}
variable "aws_elb" {}