variable "sg_frontend1" {} 
variable "frontend_port_1" {}
variable "frontend_port_2" {}
variable "frontend1" {}
variable "frontend2" {}
variable "sg_frontend2" {} 
variable "sg_frontend1_ingress_port_1" {}
variable "sg_frontend2_ingress_port_2" {}
variable "sg_frontend1_ingress_port_1" {}
variable "sg_frontend2_ingress_port_2" {}
variable "security_group_name" {} 
variable "node_name" {}
variable "backend1" {}
variable "backend2" {}
variable "sg_name" {}
variable "sg_backend1_ingress_port_1" {}
variable "sg_backend1_ingress_port_2" {}
variable "sg_backend2_ingress_port_1" {}
variable "sg_backend2_ingress_port_2" {}
variable "aws_elb" {}
variable "vpc_id" {}