variable "backend1_name" {}
variable "backend2_name" {}
variable "frontend2_name" {}
variable "frontend1_name" {}
variable "ingress_port_1" {}
variable "ingress_port_2" {}
variable "sg_name" {}
variable "my-machines-lb" {}
variable "aws_elb" {}
variable "vpc_id" {}